### ISSUE TITLE
Combine the 2 md-seed config files or allow to define location on run

### ISSUE THREAD

**Issue by JoshWhiting** [sharvit/mongoose-data-seed#16]
It seems a little overkill to require 2 config files for a seeder library at the root of a project.  With an already way to many requirements of app, env, build, test files required at the project root can you at least combine the 2 file requirements into 1?  i.e. `md-seed-config.js` has all the data required for your library?  

If not, can you allow to define the config file location when running the **md-seed** command?  i.e. `md-seed --config='./server/seeds/seed-config.js'`

**Comment by sharvit** [comment]
Thank you for filling this issue @JoshWhiting :+1: 

I will see if I can join them to one config file in version-2 https://github.com/sharvit/mongoose-data-seed/pull/13

It also make sense to allow changing the config path and from the package.json
