### ISSUE TITLE
How can I refer to previous entries if for example nested categories?

### ISSUE THREAD

**Issue by xfishernet** [sharvit/mongoose-data-seed#19]
How can I refer to previous entries if for example nested categories?

**Comment by sharvit** [comment]
I don't think I understand your question, can you expand and provide more details please?

**Comment by xfishernet** [comment]
example:

users.seeders.js
`const users = [{name: 'user1'},{name:'user2'}]`
items.seeders.js
`const users = [{user_id: ... , name: 'item1'},{user_id: ...., name:'item2'}]`

How can I get a id_ of user1 and insert into items.seeders.js?

**Comment by sharvit** [comment]
It's a question about [mongoose](https://mongoosejs.com) and not related to this project.

I guess you can do:
```js
async run() {
  const users = await User.create(usersData);
  console.log(users);
}
```
