### ISSUE TITLE
md-seed command not found

### ISSUE THREAD

**Issue by james-ingold** [sharvit/mongoose-data-seed#2]
Running the instructions from the readme, 
```
npm install --save mongoose-data-seed
md-seed init
```
command not found: md-seed. Probably need to update the docs to install globally

**Comment by sharvit** [comment]
Hi, sorry for the late response.

I always prefer to install packages locally so all my packages listed inside the `package.json`, it makes it easier to maintain and collaborate.

I personally add this export to my .zshrc or (.bashrc):
```
export PATH="./node_modules/.bin:$PATH"
```

Alternatively, it is possible to use `npm-run`:
https://github.com/timoxley/npm-run

Or you can install it globally as you mention.
