### ISSUE TITLE
Did it have any debug message when create seed failure?

### ISSUE THREAD

**Issue by davidnghk01** [sharvit/mongoose-data-seed#20]
Current when create seed failure it only have "X" icon and nothing message displayed.

Like that 
```
Seeding Results:
✖ Client
✖ ResourceServer
✖ User
```

Did it have any way to display message ? Like `DEBUG=XXX` or `NODE_ENV=XXX` something like ?

**Comment by sharvit** [comment]
Actually, it doesn't mean you had an error. The `✖` icon represent a **skiped seed** or an error.
* When it only show `✖ SeederName` it mean skipped.
* When show `✖ SeederName` and an error (with stack-trace) next to it.

Can you check your seeder `shouldRun` method.

**Comment by davidnghk01** [comment]
@sharvit I can solved the problem already. But i think it better has some debug log for indicate what happend and why it get `✖` so that debug will become much easy :)
