### ISSUE TITLE
[NPM Audit] Prototype Pollution

### ISSUE THREAD

**Issue by mzmmlds** [sharvit/mongoose-data-seed#22]
<img width="569" alt="npm-audit" src="https://user-images.githubusercontent.com/535540/60794493-870ddb80-a187-11e9-9d85-ed7fe4c5c2bf.png">

**Comment by sharvit** [comment]
Thank you for your contribution @mzmmlds :tada: 

Next release #13 should fix this issue afaik.
Would you be able to help and verify that?

Thanks!

**Comment by sharvit** [comment]
Fixed in version 2.0.0 https://github.com/sharvit/mongoose-data-seed/releases/tag/v2.0.0
