### ISSUE TITLE
Incorrect installing v 2.1.0

### ISSUE THREAD

**Issue by kprovorov** [sharvit/mongoose-data-seed#32]
When installing latest version (2.1.0) it looks like some of files are ignored. No templates folder, no bin attached, etc. Here is screenshot how it looks like inside of node_modules directory.
<img width="303" alt="Screen Shot 2019-08-04 at 12 52 46 PM" src="https://user-images.githubusercontent.com/20870537/62422167-da0b7d80-b6b6-11e9-9411-f1b55979c57a.png">

Just use `yarn add mongoose-data-seed`

if i use `yarn add mongoose-data-seed@2.0.1` (previous version) works fine

**Comment by sharvit** [comment]
Thanks for your contribution @kprovorov :1st_place_medal: 

Looks like this change made the issue:
https://github.com/sharvit/mongoose-data-seed/commit/e309a0a5dfa9991f968f5075230fc35dbb222f0a#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R20-R22

I'm working on a fix of removing the `files` attribute from the `package.json` as it should do the job.

* For me to remember, **Running tests and testing it works with `yarn lint` doesn't promise the release will actually work**

**Comment by sharvit** [comment]
@kprovorov I have just released version `2.1.1` (It will be released automatically in a few minutes :smile: ).
If the new version doesn't work for you, let me know so we can reopen the issue and look for another fix.
