### ISSUE TITLE
Cannot use ES6 imports in md-seed run command

### ISSUE THREAD

**Issue by antonkomarev** [sharvit/mongoose-data-seed#44]
I have babel packages installed in project and ES6 imports are working well, but they are not working in mongoose-data-seed.

Here are my Babel dependencies:
```
"@babel/cli": "^7.5.5",
"@babel/core": "^7.5.5",
"@babel/node": "^7.5.5",
"@babel/preset-env": "^7.5.5",
```

## I'm submitting a…

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [ ] Bug report 
* [ ] Feature request
* [ ] Documentation issue or request
* [x] Support request

## Expected Behavior

Run seeders.

## Current Behavior

Throwing exception when running `$ md-seed run`

```
/home/test-app/md-seed-config.js:1
(function (exports, require, module, __filename, __dirname) { import mongoose from 'mongoose';
                                                                     ^^^^^^^^

SyntaxError: Unexpected identifier
```

## Environment

* mongoose-data-seed version: 2.1.3
* Node version: v11.6.0
* Yarn version: 1.17.3
* Operating system: Linux

**Comment by antonkomarev** [comment]
Solved by adding `.babelrc` file with content:
```js
{
  "presets": ["@babel/preset-env"]
}
```

**Comment by sharvit** [comment]
Could you try using:
```json
{
  "presets": ["@babel/env"]
}
```

It might be related to your issue.

**Comment by sharvit** [comment]
See https://github.com/sharvit/mongoose-data-seed/blob/master/.babelrc for reference.

**Comment by antonkomarev** [comment]
I'm using this preset:
```
{
  "presets": ["@babel/preset-env"]
}
```

If I add `@babel/env`:
```
{
  "presets": ["@babel/preset-env", "@babel/env"]
}
```
It throws an error:

Error: Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

**Comment by sharvit** [comment]
Don't add, replace

**Comment by antonkomarev** [comment]
I've added plugin:
```json
"plugins": [
  "add-module-exports"
]
```

Issue replaced with another one:
> TypeError: Class constructor Seeder cannot be invoked without 'new'

I've modified preset and everything seems to work now:
```json
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": 8
        }
      }
    ]
  ],
  "plugins": [
    "add-module-exports"
  ]
}
```

Thank for the help @sharvit!

**Comment by antonkomarev** [comment]
I don't understand difference between `@babel/preset-env` & `@babel/env`, but first one works in my case.

**Comment by antonkomarev** [comment]
I've noticed that you've added comment to already solved issue and I continued to reply to you here, but mention issue #45. Moved comments with solution to appropriate issue.
