### ISSUE TITLE
"md-seed" is not recognized as an internal or external command

### ISSUE THREAD

**Issue by TheLand** [sharvit/mongoose-data-seed#6]
Hi!

I've installed your npm package with Yarn on a Feathersjs platform.
After installation I tried to launch `md-seed init` but console continues to give me this error.

I tried also with NPM 5.6 but same error message appear.

Node: 8.9.1
Yarn: 1.3.2
Windows 10 64 bit

**Comment by sharvit** [comment]
@TheLand - Thanks for filling an issue.

Can you please provide the error output?

**Comment by TheLand** [comment]
It's written in Italian

![image](https://user-images.githubusercontent.com/3605680/33942352-f5c50cae-e015-11e7-8e64-e7435da959ee.png)

`
"md-seed" is not recognized as an internal or external command, operable program or batch file.
`

My dependencies
```
"dependencies": {
    "@feathersjs/authentication": "^2.0.1",
    "@feathersjs/authentication-jwt": "^1.0.1",
    "@feathersjs/authentication-local": "^1.0.2",
    "body-parser": "^1.18.2",
    "compression": "^1.7.1",
    "cors": "^2.8.4",
    "feathers": "^2.2.3",
    "feathers-configuration": "^0.4.2",
    "feathers-errors": "^2.9.2",
    "feathers-hooks": "^2.1.2",
    "feathers-hooks-common": "^3.10.0",
    "feathers-mongoose": "^6.0.0",
    "feathers-rest": "^1.8.1",
    "feathers-socketio": "^2.0.1",
    "helmet": "^3.9.0",
    "mongoose": "^4.13.7",
    "mongoose-data-seed": "^1.0.2",
    "serve-favicon": "^2.4.5",
    "winston": "^2.4.0"
  },
```

**Comment by sharvit** [comment]
It feels same as https://github.com/sharvit/mongoose-data-seed/issues/2

You can install globally (i don't like it)
```bash
npm install -g mongoose-data-seed
```

Or use https://github.com/timoxley/npm-run which i believe is better.

**Comment by TheLand** [comment]
You are right! Great job! Thank you.

**Comment by Taiwo02** [comment]
It work for me too thanks
